const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0ZCTDlIRHZZRmtmY2dKODh1V0YzUFRvMDErY3lMYWNRYjVSNXhNM2tIVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV2VVNHFyOEZVbmFnRW5vQTVZeGFKcTM1eUROa3NQMDZyY0xxOFl0clUwTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJQy8vZ0g4amM3eG9EdDc2YXVrdVN2ZmhDcTV2ZTFVK2ZTbUFQaGRHTG04PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlSzBBL25pcjhwMmtPQnhwTXo2dzRXVWJGVUpYWFZJd0tEUnNWTzk4c3g4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhKY3o5ZWNLRktPNHdIWTFGVVdpV29kUVYvbkJLcTBCZ1NmbVh6STJ0SE09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijh1aFB3ak0rTDhtaElmMGplUVlzOCtZY2tIMk9nUlJVNGJLVVBrTTg4SEU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0psdEdhblplQ1JoakFRRlNMSVNZUS9TTUlMSTJacHZaL1dsM1R5Q2wwcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZjUxUTczN0wzWXNpSFlnUEZYdjNJSzlyY0pTTkRGSHFrYlhMT1I0eHhsRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNGeUZaTExrV1hNU1RFMlA2enAySHhlRURJK05ZVWFraGUxU1dTaXVlckdzd2FpK0dtdHhVSVdkbFJYZ1VJeWpRTEt2cnZyRUkxS0hWcHc2R2JmYkRBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODAsImFkdlNlY3JldEtleSI6InBQOGRLaVp0OVp5cUREbFB4a0IyY1VlWTlYMnN3bkRqRUMyZXFLbk9sbFE9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjNXTUU5UEdGIiwibWUiOnsiaWQiOiIyMjg5MzUwNDk3NDo4NEBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjcyNzMxMzYyMDY2NDkzOjg0QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUHF2cnVZRkVLcVJxc3NHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVXM2MWNnc2pVMmptSElGMjJUZndoRUoyV2lyTnN2UHYvY3FyQ1ZjK1RpVT0iLCJhY2NvdW50U2lnbmF0dXJlIjoia2tPWkd1L1dyRTd5MHkzclV5NEpMWEo3KzVvUW9KNnppbXdycTNjNWJsRFRQNGJiNlovMmRmVVFKWmRpQU04UHRZUFUrSDRKY2NaTWgzRFA5bkt3Q2c9PSIsImRldmljZVNpZ25hdHVyZSI6ImcvbjZ3SThzVjZZWGF3WW01TkdYYk5DUllnRmNBY0ZPL3JyeFZmMWtkZW9JQXVIQWwyZnNkcUZlYU5aeDVKWVIxbGhXWUQ2ckNpVCtTUmt1VjBRYURRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjI4OTM1MDQ5NzQ6ODRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVkxPdFhJTEkxTm81aHlCZHRrMzhJUkNkbG9xemJMejcvM0txd2xYUGs0bCJ9fV0sInBsYXRmb3JtIjoiaXBob25lIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQUlJRWdnSSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3Njg1ODk0OTEsImxhc3RQcm9wSGFzaCI6IjNnUFVKayIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQ3NMIn0=
    ",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
